FROM amazonlinux:2
MAINTAINER Daniel Boline

RUN yum install -y gcc openssl-devel && \
    curl https://sh.rustup.rs > rustup.sh && \
    sh rustup.sh -y && \
    . ~/.cargo/env && \
    rustup component add rustfmt && \
    rustup component add clippy && \
    cargo install cargo-deb

ADD build_rust_pkg.sh /root/
ADD build_rust_pkg_repo.sh /root/
ADD build_rust_pkg_deb.sh /root/

WORKDIR /workdir
