FROM rust_nightly:latest
LABEL maintainer="Daniel Boline <ddboline@gmail.com>"

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y && \
    rm -rf /var/lib/apt/lists/* && \
    . ~/.cargo/env && \
    rustup update &&
    cargo +nightly install cargo-deb
